version: '3'

services:
  users:
    container_name: users
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_HOST=db
      - JDBC_DATABASE_USERNAME=root
      - JDBC_DATABASE_PASSWORD=admin
  db:
    image: mysql:5.7.20
    container_name: users_db
    volumes:
      - ./src/main/resources/creation-scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306